// <auto-generated />
namespace InternetApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update1));
        
        string IMigrationMetadata.Id
        {
            get { return "201404090535527_Update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
