// <auto-generated />
namespace MentorMe.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class threetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(threetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201405110835438_threetable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
