// <auto-generated />
namespace MentorMe.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class errorlog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(errorlog));
        
        string IMigrationMetadata.Id
        {
            get { return "201404260511198_errorlog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
